all:
  children:
    # --- Groupes fonctionnels (par rôle) ---
    k3s_control_plane:
      hosts:
        k3s-srv-1: { ansible_host: 10.10.0.11 }
        k3s-srv-2: { ansible_host: 10.10.0.12 }
        k3s-srv-3: { ansible_host: 10.10.0.13 }
      vars:
        ansible_user: k3s-admin
    k3s_agents:
      hosts:
        k3s-agent-1: { ansible_host: 10.10.0.31 }
        k3s-agent-2: { ansible_host: 10.10.0.32 }
        k3s-agent-3: { ansible_host: 10.10.0.33 }
      vars:
        ansible_user: k3s-admin
    k3s_database:
      hosts:
        k3s-db: { ansible_host: 10.10.0.20 }
      vars:
        ansible_user: k3s-admin
        ansible_python_interpreter: /usr/bin/python3
    load_balancer:
      hosts:
        load-srv: { ansible_host: 10.10.0.10 }
      vars:
        ansible_user: alpine-admin
        ansible_python_interpreter: /usr/bin/python3
    monitoring_stack:
      hosts:
        zabbix-srv:     { ansible_host: 10.20.0.10, ansible_user: zabbix-admin }
        wazuh-srv:      { ansible_host: 10.20.0.11, ansible_user: wazuh-admin }
        prometheus-srv: { ansible_host: 10.20.0.12, ansible_user: prometheus-admin }
        grafana-srv:    { ansible_host: 10.20.0.13, ansible_user: grafana-admin }
    ansible_control:
      hosts:
        ansible-srv:
          ansible_host: 10.20.0.125
          ansible_connection: local
          ansible_user: alpine-admin
    # --- Groupes logiques (agrégations pour cibler des runs) ---
    k3s_nodes:
      children:
        k3s_control_plane:
        k3s_agents:
        k3s_database:
        load_balancer:
    wazuh_agent_targets:
      # tous les hosts qui doivent RECEVOIR l'agent Wazuh —
      # exclut wazuh-srv qui a déjà l'agent 000 natif
      children:
        k3s_nodes:
        ansible_control:
      hosts:
        zabbix-srv:     { ansible_host: 10.20.0.10, ansible_user: zabbix-admin }
        prometheus-srv: { ansible_host: 10.20.0.12, ansible_user: prometheus-admin }
        grafana-srv:    { ansible_host: 10.20.0.13, ansible_user: grafana-admin }
    zabbix_agent_targets:
      # tout le monde reçoit l'agent Zabbix, y compris wazuh-srv
      children:
        k3s_nodes:
        monitoring_stack:
        ansible_control:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/ansible
    ansible_python_interpreter: /usr/bin/python3
